language: python
sudo: required
env:
  - export DJANGO_SETTINGS_MODULE=verse.travis
python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet
script:
  - python manage.py test
