verse:
  build: .
  environment:
    - DJANGO_SETTINGS_MODULE=verse.settings
    - PYTHONUNBUFFERED=1
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/django
  ports:
    - "8000:8000"
